"""Add Vendor model

Revision ID: 43c08e1ba551
Revises: 1e769848a5c1
Create Date: 2024-08-22 18:45:58.071847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c08e1ba551'
down_revision = '1e769848a5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('piva', sa.String(length=20), nullable=False),
    sa.Column('nome_azienda', sa.String(length=100), nullable=False),
    sa.Column('indirizzo', sa.String(length=200), nullable=False),
    sa.Column('città', sa.String(length=100), nullable=False),
    sa.Column('nazione', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('piva')
    )
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_vendor_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_username'))
        batch_op.drop_index(batch_op.f('ix_vendor_email'))

    op.drop_table('vendor')
    # ### end Alembic commands ###
