"""empty message

Revision ID: 5cda5aac316e
Revises: f6ae57d6f689
Create Date: 2024-09-17 17:47:24.311344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cda5aac316e'
down_revision = 'f6ae57d6f689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indirizzo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('città', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nazione', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nazione')
        batch_op.drop_column('città')
        batch_op.drop_column('indirizzo')

    # ### end Alembic commands ###
